#!/bin/bash

if [ $# -eq 1 ]; then
        filename=`grep "\b$1\b" /etc/named.conf |sed  -e'1d' -e 's/.*\"\(.*\)\"\;/\1/g'`
elif [ $# -eq 2 ];then
        filename=`grep "$1" /etc/named.conf |sed  -e'1d' -e 's/.*\"\(.*\)\"\;/\1/g'`
else
        echo "USAGE:./edsk domain"
        exit
fi
       if [ -n "$filename" ]; then
                vi +11 $filename
        else
                echo "can't find $1!"
        fi
~


